### ISSUE TITLE
Can I perform demo.py?

### ISSUE THREAD

**Issue by ChangNamAn** [AI4Finance-Foundation/FinRL_Market_Simulator#10]
Hi, 

When I have tried to execute demo.py, I got the error messages as below.

| Arguments Remove cwd: ./OrderExecutionVecEnv-v2_PPO_0
Process Worker-3:
Traceback (most recent call last):
  File "/home/ubuntu/git/FinRL_Market_Simulator/OrderExecution/shares_data_process.py", line 29, in get_share_dicts_by_day
    trade_dates = get_trade_dates(beg_date=beg_date, end_date=end_date)
  File "/home/ubuntu/git/FinRL_Market_Simulator/OrderExecution/shares_data_process.py", line 8, in get_trade_dates
    from ideadata.stock.trade_calendar import TradeCalendar
ModuleNotFoundError: No module named 'ideadata'

Howw can I ressolve this issue?

Thanks.

**Comment by junzhejiang1234** [comment]
same problem
